// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-variants/BalanceSheet.tsx": () => import("../components/mockups/dashboard-variants/BalanceSheet.tsx"),
  "./components/mockups/dashboard-variants/CommandStrip.tsx": () => import("../components/mockups/dashboard-variants/CommandStrip.tsx"),
  "./components/mockups/dashboard-variants/PipelineLedger.tsx": () => import("../components/mockups/dashboard-variants/PipelineLedger.tsx")
};
